package com.demo.dao;

import com.demo.model.Candidate;
import org.apache.cxf.jaxrs.ext.search.SearchContext;
import java.util.Set;
import com.demo.exceptions.DaoException;
import com.demo.model.Roles;

import com.demo.dao.generic.IGenericDao;


/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface ICandidateDao extends IGenericDao<Candidate> {

		
		
	public Long getTotalCount();
	public Integer getSearchRecordCount(SearchContext context, Integer userId,Set<Roles> roleSet);
	public Candidate findByName(String lowerCase);

}
