package com.demo.service;

import java.util.List;

import com.demo.model.Candidate;

import org.apache.cxf.jaxrs.ext.search.SearchContext;

/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface ICandidateService {

	public Long getTotalCount();
public Integer getSearchRecordCount(SearchContext context);
Candidate create(Candidate candidate);
Candidate update(Candidate candidate);
List<Candidate> search(Candidate candidate);
public List<Candidate> search(SearchContext context, Integer upperLimit,
		Integer lowerLimit, String orderBy, String orderType);
		

}
